application: mkupriyanov
version: 2012
runtime: python27
api_version: 1
threadsafe: false

libraries:                                                                      
- name: jinja2                                                                  
  version: latest 

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$

handlers:
- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)
  
- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: static/\1
  upload: static/(.*\.ico)
  expiration: "7d"

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)
  expiration: "1h"
  
- url: /js/
  static_dir: static/js/

- url: /css/
  static_dir: static/css/

- url: /img/
  static_dir: static/images/

- url: /images/
  static_dir: static/images/

#- url: /repo/
#  static_dir: static/repo/
  
#- url: /tasks/checkupdate
#  script: parseFonts.app
#
#- url: /tasks/refresh
#  script: parseFonts.app
#
#- url: /tasks/dropfonts
#  script: parseFonts.app

#- url: /tasks/ttfdownloadscript
#  script: repo.app
#
#- url: /tasks/repo
#  script: repo.app


- url: /_ah/api/resources/v0.1/.*
  script: api.app

- url: /api/.*
  script: api.app


- url: /default/.*
  script: default.app
  
- url: /.*
  script: index.app
 
#- url: /.*
#  script: fontvending.app

#- url: /login/.*
#  script: asklogin.py


 #- url: /.*
 # script: not_found.py